version: '3'
services: 
  db:
    image: postgres
    ports:
      - 5433:5433
  webapi2:
    build: 
      context: .
      dockerfile: DockerFileWebApi2
    ports:
      - 8060:8060
    #networks: ["back-tier"]
    depends_on:
      - db
    
  webapi1:
    build:
      context: .
      dockerfile: DockerFileWebApi1
    ports: 
      - 8070:8070
    depends_on:
      - webapi2
    #networks: ["back-tier"]
      
  
